production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= @node[:db][:name] %>
  pool: 5
  username: <%= @node[:db][:user] %>
  password: <%= @node[:db][:password] %>
  socket: <%= @node[:db][:socket] %>
