# encoding: utf-8

require 'rubygems'
require 'thor/rake_compat'
require 'spec/rake/spectask'

class Default < Thor
  include Thor::RakeCompat

  Spec::Rake::SpecTask.new(:spec) do |t|
    t.libs << 'lib'
    t.spec_opts = ['--options', "spec/spec.opts"]
    t.spec_files = FileList['spec/**/*_spec.rb']
  end

end
