#!/bin/bash

# Setup the ssh login so that we can do stuff
# In theory if we are in the box already ssh is
# open but this documents the steps necesary for
# a local (virtual) machine.

#
# Flush all current rules from iptables
# set the default input policy to accept first 
# to avoid locking ourselves out
#
  sudo iptables -P INPUT ACCEPT
  sudo iptables -F
#
# Allow SSH connections on tcp port 22
# This is essential when working on remote servers via SSH to prevent locking yourself out of the system
#
  sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#
# Set access for localhost
#
  sudo iptables -A INPUT -i lo -j ACCEPT
#
# Accept packets belonging to established and related connections
#
  sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#
# Set default policies for INPUT, FORWARD and OUTPUT chains
#
  sudo iptables -P INPUT DROP
  sudo iptables -P FORWARD DROP
  sudo iptables -P OUTPUT ACCEPT
# Save settings
#
  sudo /sbin/service iptables save
#
# List rules
#
  sudo iptables -L -v



