#!/bin/bash
#
# Install the minimum config necesary for a Ruby environment (Ruby and Gems)
# Use Gems to install ohai and chef (and their dependencies)
#

# Make sure the package lists are up to date
sudo apt-get update

# Install the basics for Ruby
sudo apt-get install ruby1.8 ruby1.8-dev libopenssl-ruby1.8 rdoc1.8 ri1.8 irb1.8 build-essential wget

# Install RubyGems
cd /tmp
wget http://rubyforge.org/frs/download.php/57643/rubygems-1.3.4.tgz
tar zxvf rubygems-1.3.4.tgz
cd rubygems-1.3.4
sudo ruby setup.rb
sudo ln -sfv /usr/bin/gem1.8 /usr/bin/gem
cd /tmp
rm -r /tmp/rubygems*

# Add opscode gems server
sudo gem sources -a http://gems.opscode.com

# Install Chef and Ohai
sudo gem install ohai chef
