#!/bin/bash
#
# Install the minimum config necesary for a Ruby environment (Ruby and Gems)
# Use Gems to install ohai and chef (and their dependencies)
#

# Make sure the package lists are up to date
sudo dpkg-reconfigure tzdata

sudo apt-get -y update
sudo apt-get -y upgrade

# Install the basics for Ruby
sudo apt-get -y install curl git-core build-essential wget

sudo apt-get -y install bison openssl libreadline5 libreadline-dev zlib1g zlib1g-dev libssl-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev

sudo bash < <( curl -L http://bit.ly/rvm-install-system-wide )
